### ISSUE TITLE
Client autotools_ls quit with exit code 1 and signal 0

### ISSUE THREAD

**Issue by makstag** [Freed-Wu/autotools-language-server#10]
hi, please help me figure out the problem. Thanks
```
[ERROR][2024-07-24 23:02:15] .../vim/lsp/rpc.lua:770	"rpc"	"/home/bpm/.local/share/nvim/mason/bin/autotools-language-server"	"stderr"	'Traceback (most recent call last):\n  File "/home/bpm/.local/share/nvim/mason/bin/autotools-language-server", line 8, in <module>\n    sys.exit(main())\n  File "/home/bpm/.local/share/nvim/mason/packages/autotools-language-server/venv/lib/python3.10/site-packages/make_language_server/__main__.py", line 93, in main\n    MakeLanguageServer(NAME, __version__).start_io()\n  File "/home/bpm/.local/share/nvim/mason/packages/autotools-language-server/venv/lib/python3.10/site-packages/make_language_server/server.py", line 55, in __init__\n    self.parser = get_parser("make")\n  File "tree_sitter_languages/core.pyx", line 19, in tree_sitter_languages.core.get_parser\n  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language\nTypeError: __init__() takes exactly 1 argument (2 given)\n'
```
autotools-language-server  version 0.0.20

**Comment by Freed-Wu** [comment]
Are you sure it is 0.20.0? After 0.0.19 https://github.com/Freed-Wu/autotools-language-server/issues/8 , we don't use tree-sitter-languages.

**Comment by makstag** [comment]
an error occurs without this package tree-sitter-languages
```
Installing pip package autotools-language-server@0.0.20…
Collecting autotools-language-server==0.0.20 
Using cached autotools_language_server-0.0.20-py3-none-any.whl (141 kB)                
Collecting lsp-tree-sitter>=0.0.16 
Using cached lsp_tree_sitter-0.0.16-py3-none-any.whl (32 kB)   
ERROR: Could not find a version that satisfies the requirement tree-sitter-make (from autotools-language-server) (from versions: 0.0.1) 
ERROR: No matching distribution found for tree-sitter-make 
```

**Comment by Freed-Wu** [comment]
Refer #8

**Comment by makstag** [comment]
can you please provide instructions on where to screw the tree-sitter-make. Without an explanation, nothing is clear

**Comment by Freed-Wu** [comment]
Here https://github.com/Freed-Wu/autotools-language-server/issues/8#issuecomment-2178750984

Install the package by pip or poetry or other package manager, then install latest autotools-language-server.

**Comment by makstag** [comment]
don't install on ubuntu 22.04 "tree-sitter-make" package, only "tree-sitter-make == 0.0.1" and in your  requirements.txt written without a version. Building your project separately from neovim did not give any results, lsp did not work

**Comment by Freed-Wu** [comment]
What is the result of `make-language-server` in shell?

**Comment by makstag** [comment]
make-language-server  
```sh
# AUTOMATICALLY GENERATED by `shtab`



_shtab_make_language_server_option_strings=('-h' '--help' '--print-completion' '--version' '--generate-schema' '--output-format' '--indent' '--color' '--check')

_shtab_make_language_server___check_COMPGEN=_shtab_compgen_files

_shtab_make_language_server___print_completion_choices=('bash' 'zsh' 'tcsh')
_shtab_make_language_server___generate_schema_choices=('make')
_shtab_make_language_server___output_format_choices=('json' 'yaml' 'toml')
_shtab_make_language_server___color_choices=('auto' 'always' 'never')

_shtab_make_language_server__h_nargs=0
_shtab_make_language_server___help_nargs=0
_shtab_make_language_server___version_nargs=0
_shtab_make_language_server___check_nargs=*


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_${completed_positional_actions}" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 - $pos_only ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_make_language_server() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_make_language_server
  local word_index=0
  local pos_only=0 # "--" delimeter not encountered yet
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ $pos_only = 1 || " $this_word " != " -- " ]]; then
      if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" ${this_word} "* ]]; then
        # valid subcommand: add it to the prefix & reset the current action
        prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
        _set_parser_defaults
      fi

      if [[ " ${current_option_strings[@]} " == *" ${this_word} "* ]]; then
        # a new action should be acquired (due to recognised option string or
        # no more input expected from current action);
        # the next positional action can fill in here
        _set_new_action $this_word false
      fi

      if [[ "$current_action_nargs" != "*" ]] && \
         [[ "$current_action_nargs" != "+" ]] && \
         [[ "$current_action_nargs" != *"..." ]] && \
         (( $word_index + 1 - $current_action_args_start_index - $pos_only >= \
            $current_action_nargs )); then
        $current_action_is_positional && let "completed_positional_actions += 1"
        _set_new_action "pos_${completed_positional_actions}" true
      fi
    else
      pos_only=1 # "--" delimeter encountered
    fi

    let "word_index+=1"
  done

  # Generate the completions

  if [[ $pos_only = 0 && "${completing_word}" == -* ]]; then
    # optional argument started: use option strings
    COMPREPLY=( $(compgen -W "${current_option_strings[*]}" -- "${completing_word}") )
  else
    # use choices & compgen
    local IFS=$'\n' # items may contain spaces, so delimit using newline
    COMPREPLY=( $([ -n "${current_action_compgen}" ] \
                  && "${current_action_compgen}" "${completing_word}") )
    unset IFS
    COMPREPLY+=( $(compgen -W "${current_action_choices[*]}" -- "${completing_word}") )
  fi

  return 0
}

complete -o filenames -F _shtab_make_language_server make-language-server
```

**Comment by makstag** [comment]
```
[ERROR][2024-07-27 08:58:46] .../vim/lsp/rpc.lua:770	"rpc"	"/home/bpm/.local/share/nvim/mason/bin/autotools-language-server"	"stderr"	'/home/bpm/.local/share/nvim/mason/bin/autotools-language-server: 5: Syntax error: "(" unexpected\n'
```

**Comment by makstag** [comment]
What lies inside autotools-language-server
```sh
# AUTOMATICALLY GENERATED by `shtab`



_shtab_autotools_language_server_option_strings=('-h' '--help' '--print-completion' '--version' '--generate-schema' '--output-format' '--indent' '--color' '--check')

_shtab_autotools_language_server___check_COMPGEN=_shtab_compgen_files

_shtab_autotools_language_server___print_completion_choices=('bash' 'zsh' 'tcsh')
_shtab_autotools_language_server___generate_schema_choices=('make')
_shtab_autotools_language_server___output_format_choices=('json' 'yaml' 'toml')
_shtab_autotools_language_server___color_choices=('auto' 'always' 'never')

_shtab_autotools_language_server__h_nargs=0
_shtab_autotools_language_server___help_nargs=0
_shtab_autotools_language_server___version_nargs=0
_shtab_autotools_language_server___check_nargs=*


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_${completed_positional_actions}" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 - $pos_only ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_autotools_language_server() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_autotools_language_server
  local word_index=0
  local pos_only=0 # "--" delimeter not encountered yet
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ $pos_only = 1 || " $this_word " != " -- " ]]; then
      if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" ${this_word} "* ]]; then
        # valid subcommand: add it to the prefix & reset the current action
        prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
        _set_parser_defaults
      fi

      if [[ " ${current_option_strings[@]} " == *" ${this_word} "* ]]; then
        # a new action should be acquired (due to recognised option string or
        # no more input expected from current action);
        # the next positional action can fill in here
        _set_new_action $this_word false
      fi

      if [[ "$current_action_nargs" != "*" ]] && \
         [[ "$current_action_nargs" != "+" ]] && \
         [[ "$current_action_nargs" != *"..." ]] && \
         (( $word_index + 1 - $current_action_args_start_index - $pos_only >= \
            $current_action_nargs )); then
        $current_action_is_positional && let "completed_positional_actions += 1"
        _set_new_action "pos_${completed_positional_actions}" true
      fi
    else
      pos_only=1 # "--" delimeter encountered
    fi

    let "word_index+=1"
  done

  # Generate the completions

  if [[ $pos_only = 0 && "${completing_word}" == -* ]]; then
    # optional argument started: use option strings
    COMPREPLY=( $(compgen -W "${current_option_strings[*]}" -- "${completing_word}") )
  else
    # use choices & compgen
    local IFS=$'\n' # items may contain spaces, so delimit using newline
    COMPREPLY=( $([ -n "${current_action_compgen}" ] \
                  && "${current_action_compgen}" "${completing_word}") )
    unset IFS
    COMPREPLY+=( $(compgen -W "${current_action_choices[*]}" -- "${completing_word}") )
  fi

  return 0
}

complete -o filenames -F _shtab_autotools_language_server autotools-language-server
```

**Comment by Freed-Wu** [comment]
I means run `make-languageserver` in your shell (bash, zsh or others)

**Comment by makstag** [comment]
./make-language-server: 5: Syntax error: "(" unexpected

**Comment by Freed-Wu** [comment]
What is your `make-language-server`?

```sh
$ cat /usr/bin/make-langauge-server
#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from make_language_server.__main__ import main
if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    sys.exit(main())
```

**Comment by makstag** [comment]
https://github.com/Freed-Wu/autotools-language-server/issues/10#issuecomment-2253801992 It looks like this make-language-server

**Comment by Freed-Wu** [comment]
This is bash completion files. it should be in `/usr/share/bash-completion/completions/make-language-server`. I am confused why it is `/usr/bin/make-language-server`?

**Comment by makstag** [comment]
![Screenshot from 2024-07-27 11-16-04](https://github.com/user-attachments/assets/9289a4a8-3e1a-43b9-a973-f1dfc14b78b1)
I don't understand, I don't have anything along these paths

**Comment by Freed-Wu** [comment]
Can you run `python -m make_language_server --help`?

**Comment by makstag** [comment]
I copied this script https://github.com/Freed-Wu/autotools-language-server/issues/10#issuecomment-2253873768, put it to the make_language_server module in the autotools-language-server/src/ folder and ran  
![Screenshot from 2024-07-27 12-24-47](https://github.com/user-attachments/assets/79c75d33-4bea-4c7d-80d6-1c60e8dea58e)

**Comment by Freed-Wu** [comment]
> segmentation fault

Crazy. This shouldn't happened in a python program almost.

I recommend to `pip install -U` to upadte all your python programs.

**Comment by makstag** [comment]
> I recommend to `pip install -U` to upadte all your python programs.  

it didn't work

**Comment by Freed-Wu** [comment]
1. What is your enviroment? OS version, python version
2. Have you try reinstall this package?

**Comment by makstag** [comment]
1 python-venv, ubuntu 22.04, python 3.10.12  
2 yes
