### ISSUE TITLE
servers does not run

### ISSUE THREAD

**Issue by mattn** [Freed-Wu/autotools-language-server#11]
```
Traceback (most recent call last):
  File "/home/mattn/.local/share/vim-lsp-settings/servers/autotools-language-server/./venv/bin/make-language-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mattn/.local/share/vim-lsp-settings/servers/autotools-language-server/venv/lib/python3.12/site-packages/make_language_server/__main__.py", line 93, in main
    MakeLanguageServer(NAME, __version__).start_io()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mattn/.local/share/vim-lsp-settings/servers/autotools-language-server/venv/lib/python3.12/site-packages/make_language_server/server.py", line 55, in __init__
    self.parser = get_parser("make")
                  ^^^^^^^^^^^^^^^^^^
  File "tree_sitter_languages/core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by mattn** [comment]
i installed it via npm.

**Comment by Freed-Wu** [comment]
Can you try 0.0.19? https://github.com/Freed-Wu/autotools-language-server/issues/8 use the wheel of tree-sitter-make

**Comment by mattn** [comment]
```
ERROR: Ignored the following yanked versions: 0.0.1
ERROR: Could not find a version that satisfies the requirement tree-sitter-make (from autotools-language-server) (from versions: none)
WARNING: Ignoring invalid distribution ~umpy (/home/mattn/.local/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution ~umpy (/home/mattn/.local/lib/python3.10/site-packages)
ERROR: No matching distribution found for tree-sitter-make
```

**Comment by Freed-Wu** [comment]
Try

```sh
pip install tree_sitter_make-0.0.1-cp38-abi3-linux_x86_64.whl
```

The wheel comes from https://github.com/Freed-Wu/autotools-language-server/issues/8#issuecomment-2178750984

**Comment by mattn** [comment]
Same result.

```
Traceback (most recent call last):
  File "/home/mattn/.local/share/vim-lsp-settings/servers/autotools-language-server/./autotools-language-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mattn/.local/share/vim-lsp-settings/servers/autotools-language-server/venv/lib/python3.12/site-packages/make_language_server/__main__.py", line 93, in main
    MakeLanguageServer(NAME, __version__).start_io()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mattn/.local/share/vim-lsp-settings/servers/autotools-language-server/venv/lib/python3.12/site-packages/make_language_server/server.py", line 55, in __init__
    self.parser = get_parser("make")
                  ^^^^^^^^^^^^^^^^^^
  File "tree_sitter_languages/core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by Freed-Wu** [comment]
Then

```
pip install autotools-language-server==0.0.19
```

**Comment by Freed-Wu** [comment]
I think tree-sitter version is old. Try `pip install -U tree-sitter`?

**Comment by mattn** [comment]
I could fix wrong behavior.

```diff
diff --git a/src/make_language_server/utils.py b/src/make_language_server/utils.py
index cd11e91..8195516 100644
--- a/src/make_language_server/utils.py
+++ b/src/make_language_server/utils.py
@@ -15,7 +15,7 @@ SCHEMAS = {}
 QUERIES = {}
 language = Language(get_language_ptr())
 parser = Parser()
-parser.set_language(language)
+parser.language = language
 
 
 def get_query(name: str, filetype: FILETYPE = "make") -> Query:
```

**Comment by Freed-Wu** [comment]
What is:

```sh
pip list | grep tree-sitter
```

**Comment by shihtiy-tw** [comment]
Maybe related to this?

https://github.com/jwmatthews/treesitter_example/issues/1

**Comment by cxwx** [comment]
mark as same bug
