### ISSUE TITLE
Bug: `LSP Message (autotools_ls) Unexpected error in LSP server, see server's logs for details`

### ISSUE THREAD

**Issue by chrisgrieser** [Freed-Wu/autotools-language-server#3]
Thanks for this LSP, I was actually looking for some makefile tooling a while ago!

I set up autotools to be used via `nvim-lsp-config`. However, as soon as I enter an LSP server, I get this error a few dozen times per second:

```
LSP Message (autotools_ls) Unexpected error in LSP server, see server's logs for details
```

The respective LSP logs are similarly full of errors, just pasting the last few lines:
```
[ERROR][2023-11-20 14:43:11] .../vim/lsp/rpc.lua:734	"rpc"	"/opt/homebrew/bin/autotools-language-server"	"stderr"	"Failed to handle request 1635 textDocument/definition DefinitionParams(text_document=TextDocumentIdentifier(uri='file:///Users/chrisgrieser/.config/nvim/Makefile'), position=1:0, work_done_token=None, partial_result_token=None)\nTraceback (most recent call last):\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 265, in _handle_request\n    self._execute_request(msg_id, handler, params)\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 187, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/server.py\", line 96, in definition\n    for uni in DefinitionFinder(uni.node).find_all(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/finders.py\", line 146, in __init__\n    raise NotImplementedError\nNotImplementedError\n"
[ERROR][2023-11-20 14:43:11] .../vim/lsp/rpc.lua:734	"rpc"	"/opt/homebrew/bin/autotools-language-server"	"stderr"	"Error sending data\nTraceback (most recent call last):\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 265, in _handle_request\n    self._execute_request(msg_id, handler, params)\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 187, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/server.py\", line 96, in definition\n    for uni in DefinitionFinder(uni.node).find_all(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/finders.py\", line 146, in __init__\n    raise NotImplementedError\nNotImplementedError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 385, in _send_data\n    body = json.dumps(data, default=self._serialize_message)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py\", line 238, in dumps\n    **kw).encode(obj)\n          ^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py\", line 200, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py\", line 258, in iterencode\n    return _iterencode(o, 0)\n           ^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 308, in _serialize_message\n    return self._converter.unstructure(data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/cattrs/converters.py\", line 238, in unstructure\n    return self._unstructure_func.dispatch(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<cattrs generated unstructure lsprotocol.types.ResponseErrorMessage>\", line 3, in unstructure_ResponseErrorMessage\n    'error': __c_unstr_error(instance.error),\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/cattrs/converters.py\", line 960, in unstructure_optional\n    return None if val is None else _handler(val)\n                                    ^^^^^^^^^^^^^\n  File \"<cattrs generated unstructure lsprotocol.types.ResponseError>\", line 3, in unstructure_ResponseError\n    'code': instance.code,\n             ^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'code'\nFailed to handle request 1636 textDocument/references ReferenceParams(context=ReferenceContext(include_declaration=False), text_document=TextDocumentIdentifier(uri='file:///Users/chrisgrieser/.config/nvim/Makefile'), position=1:0, work_done_token=None, partial_result_token=None)\nTraceback (most recent call last):\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 265, in _handle_request\n    self._execute_request(msg_id, handler, params)\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 187, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/server.py\", line 119, in references\n    for uni in ReferenceFinder(uni.node).find_all(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/finders.py\", line 248, in __init__\n    raise NotImplementedError\nNotImplementedError\n"
[ERROR][2023-11-20 14:43:11] .../vim/lsp/rpc.lua:734	"rpc"	"/opt/homebrew/bin/autotools-language-server"	"stderr"	"Error sending data\nTraceback (most recent call last):\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 265, in _handle_request\n    self._execute_request(msg_id, handler, params)\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 187, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/server.py\", line 119, in references\n    for uni in ReferenceFinder(uni.node).find_all(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/finders.py\", line 248, in __init__\n    raise NotImplementedError\nNotImplementedError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 385, in _send_data\n    body = json.dumps(data, default=self._serialize_message)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py\", line 238, in dumps\n    **kw).encode(obj)\n          ^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py\", line 200, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py\", line 258, in iterencode\n    return _iterencode(o, 0)\n           ^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 308, in _serialize_message\n    return self._converter.unstructure(data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/cattrs/converters.py\", line 238, in unstructure\n    return self._unstructure_func.dispatch(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<cattrs generated unstructure lsprotocol.types.ResponseErrorMessage>\", line 3, in unstructure_ResponseErrorMessage\n    'error': __c_unstr_error(instance.error),\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/cattrs/converters.py\", line 960, in unstructure_optional\n    return None if val is None else _handler(val)\n                                    ^^^^^^^^^^^^^\n  File \"<cattrs generated unstructure lsprotocol.types.ResponseError>\", line 3, in unstructure_ResponseError\n    'code': instance.code,\n             ^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'code'\n"
[ERROR][2023-11-20 14:43:11] .../vim/lsp/rpc.lua:734	"rpc"	"/opt/homebrew/bin/autotools-language-server"	"stderr"	"Failed to handle request 1637 textDocument/definition DefinitionParams(text_document=TextDocumentIdentifier(uri='file:///Users/chrisgrieser/.config/nvim/Makefile'), position=1:0, work_done_token=None, partial_result_token=None)\nTraceback (most recent call last):\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 265, in _handle_request\n    self._execute_request(msg_id, handler, params)\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 187, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/server.py\", line 96, in definition\n    for uni in DefinitionFinder(uni.node).find_all(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/finders.py\", line 146, in __init__\n    raise NotImplementedError\nNotImplementedError\n"
[ERROR][2023-11-20 14:43:11] .../vim/lsp/rpc.lua:734	"rpc"	"/opt/homebrew/bin/autotools-language-server"	"stderr"	"Error sending data\nTraceback (most recent call last):\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 265, in _handle_request\n    self._execute_request(msg_id, handler, params)\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 187, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/server.py\", line 96, in definition\n    for uni in DefinitionFinder(uni.node).find_all(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/finders.py\", line 146, in __init__\n    raise NotImplementedError\nNotImplementedError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 385, in _send_data\n    body = json.dumps(data, default=self._serialize_message)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py\", line 238, in dumps\n    **kw).encode(obj)\n          ^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py\", line 200, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py\", line 258, in iterencode\n    return _iterencode(o, 0)\n           ^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/pygls/protocol/json_rpc.py\", line 308, in _serialize_message\n    return self._converter.unstructure(data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/cattrs/converters.py\", line 238, in unstructure\n    return self._unstructure_func.dispatch(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<cattrs generated unstructure lsprotocol.types.ResponseErrorMessage>\", line 3, in unstructure_ResponseErrorMessage\n    'error': __c_unstr_error(instance.error),\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/lib/python3.11/site-packages/cattrs/converters.py\", line 960, in unstructure_optional\n    return None if val is None else _handler(val)\n                                    ^^^^^^^^^^^^^\n  File \"<cattrs generated unstructure lsprotocol.types.ResponseError>\", line 3, in unstructure_ResponseError\n    'code': instance.code,\n             ^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'code'\n"
```

---

```
autotools-language-server 0.0.12
```

installed via `pip` on macOS 14.1 (M1), using Python 3.11

**Comment by Freed-Wu** [comment]
I'll take a look.

**Comment by Freed-Wu** [comment]
Can you provide your `/Users/chrisgrieser/.config/nvim/Makefile`?

**Comment by chrisgrieser** [comment]
Happens for me in any Makefile I tried. Even in a minimal one like this one:

```make
foo:
	echo
```

**Comment by Freed-Wu** [comment]
I guess it is because in this language server, Goto Defintion only work for variable, function, recipe, and will raise NotImplementation Error for other things. In my LSP plugin (coc.nvim), the error was ignored and will not disturb users, however, in other LSP plugins, (such as nvim-lsp) the error will be thrown. I'll remove the code about raise NotImplementation, just let it does nothing when it meet any things which is not variable, function, recipe.

**Comment by Freed-Wu** [comment]
Can you try #3? 

```sh
pip install git+https://github.com/Freed-Wu/autotools-language-server@iss3
```

**Comment by chrisgrieser** [comment]
Now the error changes, the LSP client exits with `Client 3 quit with exit code 1 and signal 0`, and the following is written the LSP log:

```
[START][2023-11-23 12:47:22] LSP logging initiated
[ERROR][2023-11-23 12:47:22] .../vim/lsp/rpc.lua:734	"rpc"	"/opt/homebrew/bin/autotools-language-server"	"stderr"	'Traceback (most recent call last):\n  File "/opt/homebrew/bin/autotools-language-server", line 8, in <module>\n'
[ERROR][2023-11-23 12:47:22] .../vim/lsp/rpc.lua:734	"rpc"	"/opt/homebrew/bin/autotools-language-server"	"stderr"	'    sys.exit(main())\n             ^^^^^^\n  File "/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/__main__.py", line 74, in main\n'
[ERROR][2023-11-23 12:47:22] .../vim/lsp/rpc.lua:734	"rpc"	"/opt/homebrew/bin/autotools-language-server"	"stderr"	"    from .finders import DIAGNOSTICS_FINDER_CLASSES\n"
[ERROR][2023-11-23 12:47:22] .../vim/lsp/rpc.lua:734	"rpc"	"/opt/homebrew/bin/autotools-language-server"	"stderr"	'  File "/opt/homebrew/lib/python3.11/site-packages/autotools_language_server/finders.py", line 11, in <module>\n'
[ERROR][2023-11-23 12:47:22] .../vim/lsp/rpc.lua:734	"rpc"	"/opt/homebrew/bin/autotools-language-server"	"stderr"	"    from tree_sitter_lsp.finders import (\nImportError: cannot import name 'ErrorQueryFinder' from 'tree_sitter_lsp.finders' (/opt/homebrew/lib/python3.11/site-packages/tree_sitter_lsp/finders.py)\n"
```

**Comment by Freed-Wu** [comment]
Oh, I forget to publish a new version of tree-sitter-lsp. :smile:

**Comment by Freed-Wu** [comment]
Can you use latest tree-sitter-lsp and try again?

```sh
pip install git+https://github.com/Freed-Wu/tree-sitter-lsp
```

**Comment by chrisgrieser** [comment]
yep, that works now 🥳

**Comment by Freed-Wu** [comment]
> yep, that works now

Good! The change will occur in next release.
