### ISSUE TITLE
Unable to build in NixOS. Missing setup.py!

### ISSUE THREAD

**Issue by mahmoudk1000** [Freed-Wu/autotools-language-server#5]
I have been trying to build it in NixOS as it is disabled on NUR.

This is my used config
```nix
let
    autotools-language-server = pkgs.python3.pkgs.buildPythonPackage rec {
        pname = "autotools-language-server";
        version = "0.0.13";
        src = pkgs.fetchFromGitHub {
            owner = "Freed-Wu";
            repo = pname;
            rev = "eff3e21c273c6875053d276362136d928180f3bd";
            sha256 = "sha256-GWRXF8LrxEMOI5TJgzuWCPykrAA9vKC99AP/4vBA2p0=";
        };
    };
in
```

 And this is the error. It says, that could not find `setup.py` (FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
)
 
 ```bash
 building the system configuration...
warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
error: builder for '/nix/store/cndwwjm0m24qhrhif34za714m086x4bl-python3.11-autotools-language-server-0.0.13.drv' failed with exit code 1;
       last 10 log lines:
       > Executing setuptoolsBuildPhase
       > Traceback (most recent call last):
       >   File "/build/source/nix_run_setup", line 8, in <module>
       >     exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
       >                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/tokenize.py", line 396, in open
       >     buffer = _builtin_open(filename, 'rb')
       >              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       > FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
       > /nix/store/wr08yanv2bjrphhi5aai12hf2qz5kvic-stdenv-linux/setup: line 1559: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/cndwwjm0m24qhrhif34za714m086x4bl-python3.11-autotools-language-server-0.0.13.drv'.
error: 1 dependencies of derivation '/nix/store/ld3hpybqpvrzqnkw5f9jir03ii7p3ifx-neovim-5294986.drv' failed to build
error: 1 dependencies of derivation '/nix/store/240a9fy986a0q449csjxh4g5nw8xipsy-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dqv00f3b2b67f6j494hmb0k02ywn31ls-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hhra7m1abl90yrawr9kk11l5xqhwmxw2-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/df8q7wwgl2x1v79qv0w8l2ppf0bpiswc-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/isq2pxyd9a4n2snz250wjsxan2dbqgl0-nixos-system-labbi-24.05.20231209.666fc80.drv' failed to build
 ```
 
 Could you add `setup.py` ? Do you have any idea ? Maybe I am confused 😕
 Thanks in advance

**Comment by Freed-Wu** [comment]
Perhaps <https://discourse.nixos.org/t/packaging-a-python-library-that-has-pyproject-toml-instead-of-setup-py/15120/2> should be helpful for you?

**Comment by Freed-Wu** [comment]
And the package depends on tree-sitter-languages, which is missing in NixOS <https://github.com/NixOS/nixpkgs/issues/263630>. So it cannot work and marked as broken.

**Comment by mahmoudk1000** [comment]
> Perhaps <https://discourse.nixos.org/t/packaging-a-python-library-that-has-pyproject-toml-instead-of-setup-py> should be helpful for you?

Yes, it is indeed helpful. Thanks!

**Comment by mahmoudk1000** [comment]
I have added the corresponding config to build both `tree-sitter-languages` and `tree-sitter-lsp`. And hopefully configured them correctly. But I end up with this new error, which says `OSError libstdc++.so.6: cannot open shared object file: No such file or directory`.  But I am not sure, where this come from. Any idea from your side?

And here is my [config](https://github.com/mahmoudk1000/nix-config/blob/main/modules/programs/neovim/autotools-ls.nix) as reference of how I did it.

The full log
```bash
[START][2023-12-23 19:15:23] LSP logging initiated
[ERROR][2023-12-23 19:15:23] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/qshnx9lwx0wf42kz40bgcjxzmb2cg4gs-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        'Traceback (most recent call last):\n  File "/nix/store/qshnx9lwx0wf42kz40bgcjxzmb2cg4gs-python3.11-autotools-language-server-0.0.13/bin/.autotools-language-server-wrapped", line 9, in <module>\n'
[ERROR][2023-12-23 19:15:23] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/qshnx9lwx0wf42kz40bgcjxzmb2cg4gs-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        '    sys.exit(main())\n             ^^^^^^\n  File "/nix/store/qshnx9lwx0wf42kz40bgcjxzmb2cg4gs-python3.11-autotools-language-server-0.0.13/lib/python3.11/site-packages/autotools_language_server/__main__.py", line 77, in main\n    parser = _get_parser("make")\n'
[ERROR][2023-12-23 19:15:23] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/qshnx9lwx0wf42kz40bgcjxzmb2cg4gs-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        '             ^^^^^^^^^^^^^^^^^^^\n  File "tree_sitter_languages/core.pyx", line 19, in tree_sitter_languages.core.get_parser\n'
[ERROR][2023-12-23 19:15:23] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/qshnx9lwx0wf42kz40bgcjxzmb2cg4gs-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        '  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language\n'
[ERROR][2023-12-23 19:15:23] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/qshnx9lwx0wf42kz40bgcjxzmb2cg4gs-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        '  File "/nix/store/ghmism11sn542bmm10l7s8yvwg0ixqnr-python3.11-tree-sitter-0.20.4/lib/python3.11/site-packages/tree_sitter/__init__.py", line 131, in __init__\n'
[ERROR][2023-12-23 19:15:23] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/qshnx9lwx0wf42kz40bgcjxzmb2cg4gs-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        "    self.lib = cdll.LoadLibrary(library_path)\n"
[ERROR][2023-12-23 19:15:23] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/qshnx9lwx0wf42kz40bgcjxzmb2cg4gs-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        '               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary\n'
[ERROR][2023-12-23 19:15:23] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/qshnx9lwx0wf42kz40bgcjxzmb2cg4gs-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        "    return self._dlltype(name)\n"
[ERROR][2023-12-23 19:15:23] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/qshnx9lwx0wf42kz40bgcjxzmb2cg4gs-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        '           ^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/ctypes/__init__.py", line 376, in __init__\n'
[ERROR][2023-12-23 19:15:23] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/qshnx9lwx0wf42kz40bgcjxzmb2cg4gs-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        "    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: libstdc++.so.6: cannot open shared object file: No such file or directory\n"
```

**Comment by Freed-Wu** [comment]
I guess the bug comes from tree-sitter-languages. Can you try

```python
from tree_sitter_languages import get_parser
parser = get_parser("make")
```

**Comment by mahmoudk1000** [comment]
> I guess the bug comes from tree-sitter-languages. Can you try
> 
> ```python
> from tree_sitter_languages import get_parser
> parser = get_parser("make")
> ```

I have it exclusively installed in nvim. So can't be accessed from outside. But will try tomorrow to install it in user. But I would suppose the error will remain, but will be sure then. Could you try that in your side ?

**Comment by mahmoudk1000** [comment]
I was able to fix it but ended with a new error. Still related to `tree-sitter-language`. Can't locate `languages.so: cannot open shared object file: No such file or directory`. Don't know which package is responsible for it yet.

```bash
[START][2023-12-25 19:29:18] LSP logging initiated
[ERROR][2023-12-25 19:29:18] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/5640abl01gkjgnb6hri0ihcc3j2sh4bh-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        'Traceback (most recent call last):\n  File "/nix/store/5640abl01gkjgnb6hri0ihcc3j2sh4bh-python3.11-autotools-language-server-0.0.13/bin/.autotools-language-server-wrapped", line 9, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File "/nix/store/5640abl01gkjgnb6hri0ihcc3j2sh4bh-python3.11-autotools-language-server-0.0.13/lib/python3.11/site-packages/autotools_language_server/__main__.py", line 77, in main\n'
[ERROR][2023-12-25 19:29:18] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/5640abl01gkjgnb6hri0ihcc3j2sh4bh-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        '    parser = _get_parser("make")\n             ^^^^^^^^^^^^^^^^^^^\n  File "tree_sitter_languages/core.pyx", line 19, in tree_sitter_languages.core.get_parser\n  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language\n'
[ERROR][2023-12-25 19:29:18] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/5640abl01gkjgnb6hri0ihcc3j2sh4bh-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        '  File "/nix/store/ghmism11sn542bmm10l7s8yvwg0ixqnr-python3.11-tree-sitter-0.20.4/lib/python3.11/site-packages/tree_sitter/__init__.py", line 131, in __init__\n'
[ERROR][2023-12-25 19:29:18] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/5640abl01gkjgnb6hri0ihcc3j2sh4bh-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        "    self.lib = cdll.LoadLibrary(library_path)\n"
[ERROR][2023-12-25 19:29:18] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/5640abl01gkjgnb6hri0ihcc3j2sh4bh-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        '               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary\n'
[ERROR][2023-12-25 19:29:18] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/5640abl01gkjgnb6hri0ihcc3j2sh4bh-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        '    return self._dlltype(name)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/ctypes/__init__.py", line 376, in __init__\n'
[ERROR][2023-12-25 19:29:18] .../vim/lsp/rpc.lua:675    "rpc"   "/nix/store/5640abl01gkjgnb6hri0ihcc3j2sh4bh-python3.11-autotools-language-server-0.0.13/bin/autotools-language-server" "stderr"        "    self._handle = _dlopen(self._name, mode)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^\nOSError: /nix/store/ba3l070x31pw5vbrj45n2v8an7wsbmrw-python3.11-tree-sitter-languages-1.8.0/lib/python3.11/site-packages/tree_sitter_languages/languages.so: cannot open shared object file: No such file or directory\n"
```

**Comment by Freed-Wu** [comment]
I also don't know why this bug occur. I advise to open a new issue in [py-tree-sitter-languages](https://github.com/grantjenks/py-tree-sitter-languages).

**Comment by Freed-Wu** [comment]
Before https://github.com/NixOS/nixpkgs/issues/263630 is fixed, you can get it from NUR.
