### ISSUE TITLE
Client autotools_ls quit with exit code 1 and signal 0

### ISSUE THREAD

**Issue by serpro69** [Freed-Wu/autotools-language-server#9]
Hi,

I'm getting below error from autotools language server when it's trying to start:

```
[ERROR][2024-07-03 12:30:37] .../vim/lsp/rpc.lua:770	"rpc"	"/home/sergio/.local/share/nvim/mason/bin/autotools-language-server"	"stderr"	'Traceback (most recent call last):\n  File "/home/sergio/.local/share/nvim/mason/bin/autotools-language-server", line 8, in <module>\n    sys.exit(main())\n  File "/home/sergio/.local/share/nvim/mason/packages/autotools-language-server/venv/lib/python3.10/site-packages/make_language_server/__main__.py", line 93, in main\n    MakeLanguageServer(NAME, __version__).start_io()\n  File "/home/sergio/.local/share/nvim/mason/packages/autotools-language-server/venv/lib/python3.10/site-packages/make_language_server/server.py", line 55, in __init__\n    self.parser = get_parser("make")\n  File "tree_sitter_languages/core.pyx", line 19, in tree_sitter_languages.core.get_parser\n  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language\nTypeError: __init__() takes exactly 1 argument (2 given)\n'
```

**Comment by serpro69** [comment]
> pip install tree-sitter==0.21.3 autotools-language-server

Hmm, I've installed autotools-ls with mason. Is that not supported? Or it's maybe not pulling in some dependencies?

**Comment by Freed-Wu** [comment]
Latest version should work.
